### ISSUE TITLE
Dynamic Models

### ISSUE THREAD

**Issue by anubra266** [protonemedia/laravel-cross-eloquent-search#10]
Right now it's as such 
```php
$results = Search::add(Post::class, 'title')
    ->add(Video::class, 'title')
    ->get('howto');
```
My users can check what models they want to search, which means the searched models are dynamic.
In the above method, there's no way to dynamically search only the models selected by a user.
I'm merely suggesting something that works like this.
```php
$models = [
        [Post::class,'title'],
        [Video::class, 'title']
    ];
$results = Search::addMany($models)
    ->get('howto');
```

Thanks!

**Comment by pascalbaljet** [comment]
Thanks for the suggestion, I agree this would be nice!

In the meantime, you can use the `new` method:

```php
$searcher = Search::new();

if($shouldSearchPosts) {
    $searcher->add(Post::class, 'title');
}

$results = $searcher->get('howto');
```

Might be nice to add a `when` method as well 🤔

```php
$searcher = Search::addWhen($shouldSearchPosts, Post::class, 'title');
```

**Comment by anubra266** [comment]
Thanks! I'll also keep the ```new()``` method in mind.

**Comment by pascalbaljet** [comment]
I've added both methods in 1.9.0:
https://github.com/protonemedia/laravel-cross-eloquent-search#usage

**Comment by anubra266** [comment]
Thanks a lot.
