### ISSUE TITLE
Sort by identically matched/without wildcard on the top when use startWithWildcard

### ISSUE THREAD

**Issue by KhaledLela** [protonemedia/laravel-cross-eloquent-search#14]
Search::add(Post::class, 'title')
    ->add(Video::class, 'title')
    ->startWithWildcard() // Should sort identically match/without wildcard on the top.
    ->get('os');

**Comment by pascalbaljet** [comment]
I'll add a `noWildcardSuffix()` method or something similar.

**Comment by pascalbaljet** [comment]
I've just tagged v2 with support for disabling wildcards:

```php
Search::add(Post::class, 'title')
    ->add(Video::class, 'title')
    ->endWithWildcard(false)
    ->get('github');
```

**Comment by KhaledLela** [comment]
I think this is another issue:
Let's for example have 3 different posts:
1. Title around wildcard issue.  // Key search wildcard middle.
2. Wildcard enhance issue. // Key search on the start/begging 
3. Title not most relevant with wildcard. // Key search at the end.

```
Search::add(Post::class, 'title')
    ->beginWithWildcard(false)
    ->get('wildcard');
```

**Expected results:**
2. Wildcard enhance issue. // Key search on the start/begging 
1. Title around wildcard issue.  // Key search wildcard middle.
3. Title not most relevant with wildcard. // Key search at the end.

How can we wait position of search term.

**Comment by mattvb91** [comment]
@KhaledLela did you ever get weighted search working with this package?
