### ISSUE TITLE
Support for laravel-translatable

### ISSUE THREAD

**Issue by martinsnajdr** [protonemedia/laravel-cross-eloquent-search#19]
Any chance to test / add support for https://github.com/spatie/laravel-translatable ?

Trying to get it working, but without luck yet, search always returns zero results. Also tried to use ->beginWithWildcard.

Thanks.

**Comment by martinsnajdr** [comment]
I found out that it works without soundex enabled. It's because without soundex, it uses wildcards, I didn't know that. 

But it may be useful to be able to specify in what translation the search should look...

**Comment by pascalbaljet** [comment]
For future visitors of this issue: You can also you [JSON Where Clauses](https://laravel.com/docs/8.x/queries#json-where-clauses):

```php
$lang = 'en';

$results = Search::add(Post::class, "title->{$lang}")
    ->add(Video::class, "title->{$lang}")
    ->get('howto');
```
