### ISSUE TITLE
Text matching

### ISSUE THREAD

**Issue by katesaikishore** [protonemedia/laravel-cross-eloquent-search#22]
I have using ->dontParseTerm()
I searched for this 
**Govt Says No Link Between 5G and Spread of COVID, Urges**

Where the original text in my database is 

**Govt Says No Link Between 5G and Spread of COVID, Urges Public to Not Fall for Baseless Claim**

How can I get the result if I search half-sentence also?

And with every keyword the results should be filtered how can I do that?

**Cyberpunk 2077 Sold 13.7 Million Copies Despite a Disastrous Launch**

**Cyberpunk Sold 13.7 Million Copies Despite a Launch**

I have these two in my DB
I have used the multi-search and searched Cyberpunk got two results but when I add **Cyberpunk Disastrous** the results are empty 
`->get('"Cyberpunk Disastrous"')`

**Comment by pascalbaljet** [comment]
You need to use wildcard:
https://github.com/protonemedia/laravel-cross-eloquent-search#wildcards
