### ISSUE TITLE
Query fails if database uses table prefix

### ISSUE THREAD

**Issue by gabyyro** [protonemedia/laravel-cross-eloquent-search#25]
If I use table prefix for database, there are some issues with selected columns, prefix is ignored:

`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'pages.id' in 'field list' (SQL: select pages.id as 0_page_key, pages.updated_at as 0_page_order from `dbprefix_pages` where (`dbprefix_pages`.`name` like %a%) and `dbprefix_pages`.`deleted_at` is null order by `id` asc, COALESCE(0_page_order) asc)`

**Comment by gabyyro** [comment]
Adding DB::getTablePrefix() to this method would fix it:

` public function getQualifiedKeyName(): string
    {
        return $this->qualifyColumn(\DB::getTablePrefix() . $this->getModel()->getKeyName());
    }`

**Comment by pascalbaljet** [comment]
Fixed in v2.1.0
