### ISSUE TITLE
Support for DB::raw() fields

### ISSUE THREAD

**Issue by Freezon** [protonemedia/laravel-cross-eloquent-search#31]
There are fields with json type, there is a need to search by field using DB::raw() field name

**Comment by pascalbaljet** [comment]
This is already supported, for example, if you're using translations:

```
$results = Search::add(Post::class, 'title->en')
    ->add(Video::class, 'title->en')
    ->get('howto');
```

**Comment by pascalbaljet** [comment]
There is a `ignoreCase` method, but I forgot to put it in the docs 😅

**Comment by ccchapman** [comment]
Ah @pascalbaljet! I see that. It looks like it works for searching/where clauses. How about the order by part?
