### ISSUE TITLE
syntax error at or near "0" (Postgres DB)

### ISSUE THREAD

**Issue by richstandbrook** [protonemedia/laravel-cross-eloquent-search#32]
I don't know if this is a PostgreSQL thing, but I'm doing anything special, but I'm getting an SQL syntax error

```php
\ProtoneMedia\LaravelCrossEloquentSearch\Search::new()
                    ->add(Group::class)
                    ->add(Document::class)
                    ->get()
```

```
Illuminate/Database/QueryException with message 'SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near "0"
LINE 1: (select groups.id as 0_group_key, groups.updated_at as 0_gro...
                             ^ (SQL: (select groups.id as 0_group_key, groups.updated_at as 0_group_order, null as 1_document_key, null as 1_document_order from "groups" where "groups"."deleted_at" is null) union (select null as 0_group_key, null as 0_group_order, documents.id as 1_document_key, documents.updated_at as 1_document_order from "documents" where "documents"."deleted_at" is null) order by COALESCE(0_group_order,1_document_order) asc)'
```

I don't know if it just doesn't like the `0_` prefix or whats going on here

**Comment by richstandbrook** [comment]
Ok, just read the requirements! Never mind, I'll keep looking for a solution!

**Comment by pascalbaljet** [comment]
I made an attempt once to support PostgreSQL and SQLite, but I guess there's too much magic going on, and I don't have much experience with PostgreSQL, to be honest 😅

https://github.com/protonemedia/laravel-cross-eloquent-search/runs/3765016233?check_suite_focus=true

**Comment by fulopattila122** [comment]
I've made a fork that supports both Postgres and SQLite. Not all the features though, as of now:

| Feature                | MySQL 8 | PostgreSQL | SQLite  |
|------------------------|---------|------------|---------|
| Multi-model search     | ✔       | ✔          | ✔       |
| Multi-model pagination | ✔       | ✔          | ✔       |
| Search in JSON fields  | ✔       | ✔          | ✔       |
| Full Text Search       | ✔       | ❌          | ❌       |
| Sort by Model Order    | ✔       | ❌          | ❌       |

My original aim was to submit a PR to this repo, but in the meantime, it deviated a lot from the original code.
I thought it wouldn't get an easy approval from Pascal, and I needed PostgreSQL support urgently, so I released it as a separate package under a different namespace:

https://github.com/artkonekt/search
