### ISSUE TITLE
Check if updated_at column is defined

### ISSUE THREAD

**Issue by MeiKatz** [protonemedia/laravel-cross-eloquent-search#39]
While on my research about how to implement this package for SQLite3 I discovered that it has a fallback on to the `updated_at` column for ordering if no column was specified. I think we should check if `->timestamps` is `true` and otherwise maybe fallback to the primary column? Or maybe any other column that is definitely defined

**Comment by pascalbaljet** [comment]
I've opened a PR (#44) to address this, but it's a breaking change, so I'll keep it open until the next major release.

**Comment by pascalbaljet** [comment]
Fixed in [v3.0.0](https://github.com/protonemedia/laravel-cross-eloquent-search/releases/tag/3.0.0).
