### ISSUE TITLE
Search Term is empty when I go to next page

### ISSUE THREAD

**Issue by LeonBuchner** [protonemedia/laravel-cross-eloquent-search#40]
Hello,
when I search for something and I will get multiple result pages my search term will be empty after going to page 2.

Example: I search for order where first_name is "max". Everything is right. When I go to page 2 of the results I will get all orders and not only orders where first_name is max.

My Code:

     $term = $request->query('term'); // i.e Max

        $orders = Search::add(Order::orderBy('created_at', 'desc'), ['invoice_number', 'first_name', 'last_name', 'street', 'additional_address', 'city', 'state', 'house_number', 'zip_code'])
            ->beginWithWildcard()
            ->paginate(10)
            ->get($term);

**Comment by pascalbaljet** [comment]
You need to use the `withQueryString` method: https://laravel.com/docs/8.x/pagination#appending-query-string-values

**Comment by LeonBuchner** [comment]
I work with laravel since a few years now but never noticed this function 😅
May you add this to the documentation please?
