### ISSUE TITLE
Call to undefined method ProtoneMedia\LaravelCrossEloquentSearch\Searcher::includeModelType()

### ISSUE THREAD

**Issue by radinmehr** [protonemedia/laravel-cross-eloquent-search#46]
I'm using laravel-cross-eloquent-search version 2.4.
When I was trying to use `->includeModelType()` to get the type I got the following error:

> Call to undefined method ProtoneMedia\LaravelCrossEloquentSearch\Searcher::includeModelType()

I checked the `Searcher.php` file, but there isn't any method with this name (I found only g`etModelsPerType()` method). How can I know which model is producing the result?
How can I fix this problem?

**Comment by pascalbaljet** [comment]
You need to update to v2.6 :)
