### ISSUE TITLE
includeModelType() not found

### ISSUE THREAD

**Issue by muarachmann** [protonemedia/laravel-cross-eloquent-search#48]
Hello and +1 for this package. However, I am using `2.4` and noticed this method no longer works or has been removed. Was this intended or the docs needs to be updated @pascalbaljet

**Comment by muarachmann** [comment]
I get the following error
`Call to undefined method ProtoneMedia\LaravelCrossEloquentSearch\Searcher::includeModelType()`

**Comment by pascalbaljet** [comment]
That method was introduced in v2.6.
