### ISSUE TITLE
type addition each row

### ISSUE THREAD

**Issue by bsormagec** [protonemedia/laravel-cross-eloquent-search#5]
Hello,
if you can add type(class_basename or model_name) column each row it will be better solution, how we can handle when we are using API service ? On your example you are using blade but we arent. Can you please add an option to add each row to type. Thanks. @pascalbaljet

**Comment by pascalbaljet** [comment]
I don't fully understand your question. This package is independent from Blade, you don't have to use it with Blade. You can use [API Resources](https://laravel.com/docs/8.x/eloquent-resources) or something like [Fractal](https://github.com/thephpleague/fractal) to transform the results.

When looping through the results, you can get the class of an item by using the `get_class()` method:

```php
Search::add(Post::class, 'title')
    ->add(Video::class, 'title')
    ->get('howto')
    ->map(function($item) {
        $class = get_class($item);
    });
```

**Comment by bsormagec** [comment]
I wants to tell i am using 3 different model on search and for example **User::class, Lesson::class, Course::class**

When Search return us response. We dont know which one coming from which model. 

For example 

`[
{
"name":"Burak",
"id" : "1"
},
{
"name": "Lesson 1",
"id": "3"
},
{
"name": "Laravel",
"id": 12
}
]`

I am telling about add type column to each row you can see example below.

`[
{
"row" : {
"name":"Burak",
"id" : "1",
},
"type": "user"
},
{
"row": {"name": "Lesson 1",
"id": "3"},
"type":"lesson"
},
{
"row": {
"name": "Laravel",
"id": 12},
"type": "course"
}
]`
This is an example only, you can find more clever way if you want. Just need this always.

Thanks

**Comment by KhaledLela** [comment]
> I wants to tell i am using 3 different model on search and for example **User::class, Lesson::class, Course::class**
> 
> When Search return us response. We dont know which one coming from which model.
> 
> For example
> 
> `[ { "name":"Burak", "id" : "1" }, { "name": "Lesson 1", "id": "3" }, { "name": "Laravel", "id": 12 } ]`
> 
> I am telling about add type column to each row you can see example below.
> 
> `[ { "row" : { "name":"Burak", "id" : "1", }, "type": "user" }, { "row": {"name": "Lesson 1", "id": "3"}, "type":"lesson" }, { "row": { "name": "Laravel", "id": 12}, "type": "course" } ]`
> This is an example only, you can find more clever way if you want. Just need this always.
> 
> Thanks

Inside map function you can iterate over all result and introduce type based on `instanceOf` model.

    ->map(function($item) {
           if ($item instanceof User) {
               $item->type = 'user';
           }
           elseif ($item instanceof Lesson) {
               $item->type = 'lesson';
           }
           elseif ($item instanceof Course) {
               $item->type = 'course';
           }

        return $item;
    });

**Comment by bsormagec** [comment]
I know this method just telling you can add this feature to package as a method we can call it only "**withGroupedInstance**" for example. I see that but this need manual works for each search models. I just want to automate it inside package.

Thank you for your offers :)
