### ISSUE TITLE
duplicate result in pagination

### ISSUE THREAD

**Issue by SidneySaints** [protonemedia/laravel-cross-eloquent-search#55]
hi,

if i call the paginate or simplePaginate method some results seem to appear again and again on different pages.
Currently I cannot find the cause of the problem. Does anyone else have this problem?

Or am i doing something wrong?

My function at my data repository
```php
 public function testCasesSearch(string $result = null, Carbon $from = null, Carbon $to = null): Searcher
    {
        $query = $result ? $this->testCases()->where('result', $result) : $this->testCases();
        return Search::add($query, ['first_name', 'last_name', 'result', 'email', 'phone']);
    }
```
The Controller
```php
public function testCases(
        CompanyCollection $company,
        Request $request
    ): JsonResponse
    {

        return response()->json(
            $company->testCasesSearch($request->get('result'))
                ->paginate(15, 'page', $request->get('page'))
                ->get($request->get('term'))
        );
    }
```

**Comment by pascalbaljet** [comment]
The `updated_at` column probably contains a lot of equal values. See also https://github.com/protonemedia/laravel-cross-eloquent-search/issues/47#issuecomment-1025591817
