### ISSUE TITLE
search based on database-encryption

### ISSUE THREAD

**Issue by constantinosergiou** [protonemedia/laravel-cross-eloquent-search#61]
is it possible? to be handle and how?

e.g first_name , last_name , are encrypted

**Comment by constantinosergiou** [comment]
with openssl_encrypt it can be done :) fixed

**Comment by pascalbaljet** [comment]
@constantinosergiou could you elaborate?

**Comment by constantinosergiou** [comment]
@pascalbaljet  
i was experiment , so as i far a found on my notes! 

```
$encrypt_method = "aes-128-ecb";
$decryptData =  openssl_encrypt($request['query'], $encrypt_method, substr(hash('sha256', env('APP_KEY')), 0, 16), 0, $iv = '');


    $query = Search::new()
     ->add($users,  ['first_name', 'last_name','role.slug'])
     ->paginate(\Request::get('per_page') ?: 30)->search($decryptData );
                             ```
                             @pascalbaljet  can you elaborate on this https://github.com/protonemedia/laravel-cross-eloquent-search/issues/60  ? 
                             thank you

**Comment by constantinosergiou** [comment]
@pascalbaljet  please elaborate on this 
       https://github.com/protonemedia/laravel-cross-eloquent-search/issues/60  
                             thank you
