### ISSUE TITLE
Installation 

### ISSUE THREAD

**Issue by blessingchirume** [protonemedia/laravel-cross-eloquent-search#64]
I have installed the packed via composer but when I call Search class it still says class undefined 
<img width="347" alt="image" src="https://user-images.githubusercontent.com/61548727/174707131-8f508a75-1c1b-4d9b-be65-d38ce84c3ee6.png">

**Comment by pascalbaljet** [comment]
Please share a code example.

**Comment by blessingchirume** [comment]
So I discovered I had to restart my vs code then it worked perfectly. Thank
you
