### ISSUE TITLE
<!-- Target class [laravel-cross-eloquent-search] does not exist. (500 Internal Server Error) -->

### ISSUE THREAD

**Issue by legendoscar** [protonemedia/laravel-cross-eloquent-search#67]
Hello good works here! I am using this package on Lumen and followed the instructions to install. 

My controller (->search() was returning errors so i used ->get())
![image](https://user-images.githubusercontent.com/37835229/191188892-d45fb804-9c3d-4438-b677-0931dd02fb41.png)

My error trace
![image](https://user-images.githubusercontent.com/37835229/191190468-d69264c1-f7e5-4bce-be8e-4e6ca27d1cfb.png)

The error output on Postman
![image](https://user-images.githubusercontent.com/37835229/191190889-a6812e25-40fc-45c0-812c-3b5fceb4a32a.png)

**Comment by pascalbaljet** [comment]
This package is not compatible with Lumen.
