### ISSUE TITLE
Support simplePaginate()

### ISSUE THREAD

**Issue by mewejo** [protonemedia/laravel-cross-eloquent-search#7]
Hi,

I will submit this as a PR this time.. I should have time over Christmas to do it :) 

Would you be happy with an option to use `simplePaginate()` vs `paginate()`? If so, do you have any preference on how it's implemented?

**Comment by pascalbaljet** [comment]
I'm fine with that! I think it would be nice to have a boolean property `$simplePaginate` which defaults to `false`. With a `simplePaginate` you'd be able to set that property to `true`. Then in the `getIdAndOrderAttributes` method there should be a check how to paginate.

Migrating `private` properties to `protected` is fine as well, so I'll close #8 :)

**Comment by mewejo** [comment]
Fantastic, I'm hoping to look at this tomorrow! 😀

**Comment by pascalbaljet** [comment]
Thanks for the PR! I've changed it a little bit so only have to call the `simplePaginate` method (see docs).

**Comment by mewejo** [comment]
Perfect, it did feel a bit weird as I wrote it but left it incase you wanted it explicit.

That change looks great.

Thanks again!
