### ISSUE TITLE
No SearchController.php file

### ISSUE THREAD

**Issue by musiccollect** [protonemedia/laravel-cross-eloquent-search#83]
On a fresh install of this plugin to Laravel 10, Filament 3.

Your video walkthrough at https://www.youtube.com/watch?v=WigAaQsPgSA
and also this related https://www.youtube.com/watch?v=VzQ0aXi8f80 both refer to a App\Http\Controllers\SearchController.php file ... but this does not appear to be created during install.

**Comment by krekas** [comment]
Why it should create? You must create controllers yourself. And filament have nothing to do with search using this package.
