### ISSUE TITLE
Sort results by nested relationship

### ISSUE THREAD

**Issue by spartyboy** [protonemedia/laravel-cross-eloquent-search#9]
I want to sort main result set by relation in an order.. eg lets say a post has many tags i want to get all post but they should be sorted by their tags using eager load.

**Comment by pascalbaljet** [comment]
Something likes this? (from the Laravel docs)

```php
$orderBySubquery = Flight::select('arrived_at')
    ->whereColumn('destination_id', 'destinations.id')
    ->orderBy('arrived_at', 'desc')
    ->limit(1);

Search::add(Destination::class, 'location', $orderBySubquery)->get('Amsterdam');
```

**Comment by spartyboy** [comment]
Yea so all destinations result would be ordered by flight order by

**Comment by pascalbaljet** [comment]
For future readers of this issue, I recommend looking at this package: https://github.com/kirschbaum-development/eloquent-power-joins
